from .LoginView import LoginView
from .LogoutView import LogoutView
from .ChangePasswordView import ChangePasswordView
from .RegistrationView import RegistrationView
from .EmailVerificationView import EmailVerificationView
from .NewOtpGenerationView import NewOtpGenerationView
from .ForgotPasswordView import ForgotPasswordView
from .VerifyOTPView import VerifyOTPView
from .ResetPasswordView import ResetPasswordView