# Generated by Django 5.0.2 on 2024-05-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='denomination',
            field=models.CharField(choices=[('CTL', 'Catholic'), ('ADV', 'Adventist'), ('ISL', 'Islamic'), ('PRO', 'Protestant'), ('OTH', 'Other')], max_length=20),
        ),
    ]
