# Generated by Django 5.0.2 on 2024-05-16 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_denomination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('denomination', models.CharField(choices=[('CTL', 'Catholic'), ('ADV', 'Adventist'), ('ISL', 'Islamic'), ('PRO', 'Protestant'), ('OTH', 'Other')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='temporary-pictures/')),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'temporary_profiles',
            },
        ),
    ]
