# Generated by Django 5.0.2 on 2024-05-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_temporaryprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryprofile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='temporaryprofile',
            name='denomination',
            field=models.CharField(choices=[('CTL', 'Catholic'), ('ADV', 'Adventist'), ('ISL', 'Islamic'), ('PRO', 'Protestant'), ('OTH', 'Other')], default='OTH', max_length=20),
        ),
        migrations.AlterField(
            model_name='temporaryprofile',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='temporaryprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile-pictures/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='denomination',
            field=models.CharField(choices=[('CTL', 'Catholic'), ('ADV', 'Adventist'), ('ISL', 'Islamic'), ('PRO', 'Protestant'), ('OTH', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
