# Generated by Django 5.0.2 on 2024-05-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_temporaryprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='temporary-profile-pictures/'),
        ),
    ]
