# Generated by Django 5.0.2 on 2024-05-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_temporaryprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='temporary-profile-pictures/default.jpg', null=True, upload_to='temporary-profile-pictures/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile-pictures/default.jpg', null=True, upload_to='profile-pictures/'),
        ),
    ]
