# Generated by Django 5.0.2 on 2024-05-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_temporaryprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryprofile',
            name='denomination',
            field=models.CharField(choices=[('CTH', 'Catholic'), ('ADV', 'Adventist'), ('ISL', 'Islamic'), ('PRO', 'Protestant'), ('OTH', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='denomination',
            field=models.CharField(choices=[('CTH', 'Catholic'), ('ADV', 'Adventist'), ('ISL', 'Islamic'), ('PRO', 'Protestant'), ('OTH', 'Other')], max_length=20, null=True),
        ),
    ]
