# Generated by Django 5.0.2 on 2024-05-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_temporaryprofile_denomination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
