# Generated by Django 5.0.2 on 2024-05-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_temporaryprofile_gender_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryprofile',
            name='denomination',
            field=models.CharField(choices=[('Catholic', 'Catholic'), ('Adventist', 'Adventist'), ('Islamic', 'Islamic'), ('Protestant', 'Protestant'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='temporaryprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='denomination',
            field=models.CharField(choices=[('Catholic', 'Catholic'), ('Adventist', 'Adventist'), ('Islamic', 'Islamic'), ('Protestant', 'Protestant'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
