# Generated by Django 5.0.2 on 2024-05-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_hobbie_hobbieprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbie',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='my_hobbies', through='profiles.HobbieProfile', to='profiles.userprofile'),
        ),
    ]
