# Generated by Django 5.0.2 on 2024-05-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_hobbie_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbie',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='hobbies', through='profiles.HobbieProfile', to='profiles.userprofile'),
        ),
    ]
