from .UserChatsView import UserChatsView
from .ChatDetailsView import ChatDetailsView
from .DeleteMessageView import DeleteMessageView
from .DeleteMessageForMeView import DeleteMessageForMeView
from .DeleteMessageForEveryoneView import DeleteMessageForEveryoneView
from .DeleteChatView import DeleteChatView
from .CreateOrActivateChatView import CreateOrActivateChatView
from .SendMessageView import SendMessageView