# Generated by Django 5.0.2 on 2024-05-16 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_customuser_is_verified_emailotp'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emailotp',
            table='OTP',
        ),
    ]
