# Generated by Django 5.0.2 on 2024-05-17 08:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_customuser_transfer_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='temp_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
