# Generated by Django 5.0.2 on 2024-05-18 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_emailotp_temp_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
