# Generated by Django 5.0.2 on 2024-05-25 21:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0008_block'),
        ('userauth', '0009_customuser_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blockers',
            field=models.ManyToManyField(blank=True, related_name='blocked_users', through='chatapp.Block', to=settings.AUTH_USER_MODEL),
        ),
    ]
